/**
 * Bounty Crank — Automated Payout Executor
 *
 * Runs every hour. Fetches all BountyAccount PDAs with status = PendingReview,
 * checks whether the 48-hour optimistic review window has expired, and
 * executes `execute_payout` for any that qualify. This is what makes the
 * "silence is golden" happy path feel seamless to translators.
 */

import * as anchor from '@coral-xyz/anchor';
import {
  Connection,
  Keypair,
  PublicKey,
  clusterApiUrl,
} from '@solana/web3.js';
import {
  getAssociatedTokenAddressSync,
  TOKEN_PROGRAM_ID,
} from '@solana/spl-token';
import cron from 'node-cron';
import 'dotenv/config';

// ─── Config ─────────────────────────────────────────────────────────────────

const PROGRAM_ID = new PublicKey(
  process.env.BOUNTY_PROGRAM_ID ?? 'EZs9aybYZxSdSL8t1fCD2iXcpYHidsYQa44KttCRZFAs'
);
const USDC_MINT = new PublicKey(
  // Devnet USDC mint (Circle's official devnet USDC)
  process.env.USDC_MINT ?? '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU'
);
const REVIEW_WINDOW_SECS = 48 * 60 * 60;
const CRON_SCHEDULE = process.env.CRANK_SCHEDULE ?? '0 * * * *'; // every hour

// ─── IDL (generated by `anchor build`) ──────────────────────────────────────
// Replace with the auto-generated IDL from anchor/target/idl/bounty.json
// eslint-disable-next-line @typescript-eslint/no-require-imports
const IDL = require('../../anchor/target/idl/translation_bounty.json');

// ─── Wallet & Connection ─────────────────────────────────────────────────────

function loadCrankKeypair(): Keypair {
  const raw = process.env.CRANK_PRIVATE_KEY;
  if (!raw) throw new Error('CRANK_PRIVATE_KEY env var is required');
  const bytes = JSON.parse(raw) as number[];
  return Keypair.fromSecretKey(Uint8Array.from(bytes));
}

function buildProvider(keypair: Keypair): anchor.AnchorProvider {
  const rpcUrl =
    process.env.SOLANA_RPC_URL ?? clusterApiUrl('devnet');
  const connection = new Connection(rpcUrl, 'confirmed');
  const wallet = new anchor.Wallet(keypair);
  return new anchor.AnchorProvider(connection, wallet, {
    commitment: 'confirmed',
  });
}

// ─── PDA helpers (must match the Rust seeds) ─────────────────────────────────

function bountyPda(author: PublicKey, nonce: bigint): [PublicKey, number] {
  const nonceBuf = Buffer.alloc(8);
  nonceBuf.writeBigUInt64LE(nonce);
  return PublicKey.findProgramAddressSync(
    [Buffer.from('bounty'), author.toBuffer(), nonceBuf],
    PROGRAM_ID
  );
}

function vaultPda(bountyAccount: PublicKey): [PublicKey, number] {
  return PublicKey.findProgramAddressSync(
    [Buffer.from('bounty_vault'), bountyAccount.toBuffer()],
    PROGRAM_ID
  );
}

// ─── Status enum (must mirror BountyStatus in lib.rs) ────────────────────────

enum BountyStatus {
  Open = 0,
  Claimed = 1,
  PendingReview = 2,
  Disputed = 3,
  Paid = 4,
}

interface BountyAccountData {
  author: PublicKey;
  translator: PublicKey | null;
  admin: PublicKey;
  rewardAmount: anchor.BN;
  originalTxId: string;
  translatedTxId: string | null;
  submissionTimestamp: anchor.BN;
  status: { open?: object; claimed?: object; pendingReview?: object; disputed?: object; paid?: object };
  nonce: anchor.BN;
  bump: number;
  vaultBump: number;
}

// ─── Core crank logic ────────────────────────────────────────────────────────

async function runCrank(): Promise<void> {
  const keypair = loadCrankKeypair();
  const provider = buildProvider(keypair);
  anchor.setProvider(provider);

  // Anchor 0.30+: program ID is embedded in the IDL — pass only (idl, provider)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const program = new anchor.Program(IDL as any, provider);

  console.log('[crank] Fetching all BountyAccount PDAs…');

  // Fetch every account owned by the bounty program
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const allBounties: Array<{ publicKey: PublicKey; account: BountyAccountData }> = await (program.account as any)['bountyAccount'].all();

  console.log(`[crank] Found ${allBounties.length} total bounty accounts`);

  const nowSecs = Math.floor(Date.now() / 1000);

  const eligible = allBounties.filter((b: { publicKey: PublicKey; account: BountyAccountData }) => {
    const data = b.account as unknown as BountyAccountData;
    const isPendingReview = 'pendingReview' in data.status;
    const submissionTs = data.submissionTimestamp.toNumber();
    const windowExpired = nowSecs > submissionTs + REVIEW_WINDOW_SECS;
    return isPendingReview && windowExpired;
  });

  console.log(`[crank] ${eligible.length} bounties ready for payout`);

  for (const b of eligible) {
    const data = b.account as unknown as BountyAccountData;
    const bountyPubkey = b.publicKey;

    if (!data.translator) {
      console.warn(`[crank] ${bountyPubkey} is PendingReview but has no translator — skipping`);
      continue;
    }

    const translatorPubkey = data.translator;
    const translatorTokenAccount = getAssociatedTokenAddressSync(
      USDC_MINT,
      translatorPubkey
    );

    const [vault] = vaultPda(bountyPubkey);

    try {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const sig = await (program.methods as any)
        .executePayout()
        .accounts({
          cranker: keypair.publicKey,
          bountyAccount: bountyPubkey,
          vault,
          translatorTokenAccount,
          usdcMint: USDC_MINT,
          tokenProgram: TOKEN_PROGRAM_ID,
        })
        .rpc();

      console.log(
        `[crank] ✓ Payout executed for bounty ${bountyPubkey.toBase58()} → translator ${translatorPubkey.toBase58()}. Sig: ${sig}`
      );
    } catch (err: unknown) {
      // Log and continue — one failed payout shouldn't block the others
      const message = err instanceof Error ? err.message : String(err);
      console.error(
        `[crank] ✗ Failed to execute payout for ${bountyPubkey.toBase58()}: ${message}`
      );
    }
  }

  console.log('[crank] Sweep complete');
}

// ─── Entry point ─────────────────────────────────────────────────────────────

console.log(`[crank] Starting. Schedule: "${CRON_SCHEDULE}"`);

// Run once immediately on startup, then on the schedule
runCrank().catch(console.error);

cron.schedule(CRON_SCHEDULE, () => {
  runCrank().catch(console.error);
});
